blueprint:
  name: Traffic Monitoring with Telegram Notifications
  description: |
    Monitor Waze Travel Time sensor and send smart Telegram notifications based on traffic conditions.

    Features integrated failsafe logic that eliminates the need for separate failsafe automations.

    **Key Features:**
    - Integrated failsafe counter tracks consecutive sensor failures
    - Configurable polling interval and failsafe threshold
    - Failsafe message sent only if no traffic message was sent
    - Adaptive to any polling interval
    - No duplicate messages (single notification per monitoring window)

    **Available Message Placeholders:**

    Traffic Messages (Heavy/Normal/Light):
    - {travel_time} - Current travel time in minutes
    - {distance} - Route distance (shows "N/A" if unavailable)
    - {distance_unit} - Distance unit (km or mi)
    - {route} - Route description (shows "N/A" if unavailable)

    Failsafe Message:
    - {failsafe_threshold} - Number of failed polls configured
    - {failsafe_duration} - Duration in minutes (threshold Ã— interval)
    - {google_maps_link} - Map directions link (Google Maps, OpenStreetMap, or custom)

    **Default Messages:**
    All message templates can be customized. Use the placeholders above in your custom messages.
  domain: automation
  input:
    waze_sensor:
      name: Waze Travel Time Sensor
      description: The Waze travel time sensor to monitor (or any numeric sensor for debugging)
      selector:
        entity:
          filter:
            - domain: sensor

    traffic_state_helper:
      name: Traffic State Helper
      description: input_select helper to track traffic state (prevents duplicate notifications)
      selector:
        entity:
          filter:
            - domain: input_select

    failed_attempts_counter:
      name: Failed Attempts Counter
      description: input_number helper to track sensor failures for failsafe logic
      selector:
        entity:
          filter:
            - domain: input_number

    telegram_target:
      name: Telegram Chat ID
      description: Your Telegram chat ID for notifications
      selector:
        text:

    monitoring_start:
      name: Monitoring Start Time
      description: When to start polling the sensor (e.g., "07:30:00")
      default: "07:30:00"
      selector:
        time:

    monitoring_end:
      name: Monitoring End Time
      description: When to stop polling the sensor (e.g., "09:00:00")
      default: "09:00:00"
      selector:
        time:

    light_traffic_threshold:
      name: Light Traffic Threshold (minutes)
      description: Travel time below this triggers light traffic notification (must be less than heavy threshold)
      default: 50
      selector:
        number:
          min: 20
          max: 120
          step: 5
          unit_of_measurement: "min"

    heavy_traffic_threshold:
      name: Heavy Traffic Threshold (minutes)
      description: Travel time above this triggers heavy traffic warning (must be greater than light threshold)
      default: 60
      selector:
        number:
          min: 30
          max: 180
          step: 5
          unit_of_measurement: "min"

    active_days:
      name: Active Days
      description: Select which days the automation should run
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
      selector:
        select:
          multiple: true
          options:
            - label: "Monday"
              value: "mon"
            - label: "Tuesday"
              value: "tue"
            - label: "Wednesday"
              value: "wed"
            - label: "Thursday"
              value: "thu"
            - label: "Friday"
              value: "fri"
            - label: "Saturday"
              value: "sat"
            - label: "Sunday"
              value: "sun"

    polling_interval:
      name: Polling Interval (minutes)
      description: How often to check the sensor during monitoring window
      default: 5
      selector:
        number:
          min: 1
          max: 30
          step: 1
          unit_of_measurement: "min"

    failsafe_threshold:
      name: Failsafe Threshold (failed polls)
      description: Number of consecutive failed polls before sending failsafe message
      default: 3
      selector:
        number:
          min: 1
          max: 10
          step: 1
          unit_of_measurement: "polls"

    distance_unit:
      name: Distance Unit
      description: Unit for distance display (must match your Waze sensor configuration)
      default: "km"
      selector:
        select:
          options:
            - label: "Kilometers (km)"
              value: "km"
            - label: "Miles (mi)"
              value: "mi"

    heavy_traffic_title:
      name: Heavy Traffic Message Title
      description: Title for heavy traffic notification
      default: "ðŸš¨ Traffic Alert"
      selector:
        text:

    heavy_traffic_message:
      name: Heavy Traffic Message
      description: Message body for heavy traffic (use {travel_time}, {distance}, {distance_unit}, {route})
      default: |
        Heavy traffic!

        â±ï¸ Travel time: {travel_time} minutes
        ðŸ“ Distance: {distance} {distance_unit}
        ðŸ›£ï¸ Route: {route}
      selector:
        text:
          multiline: true

    normal_traffic_title:
      name: Normal Traffic Message Title
      description: Title for normal traffic notification
      default: "â„¹ï¸ Normal Traffic"
      selector:
        text:

    normal_traffic_message:
      name: Normal Traffic Message
      description: Message body for normal traffic (use {travel_time}, {distance}, {distance_unit}, {route})
      default: |
        Normal traffic conditions.

        â±ï¸ Travel time: {travel_time} minutes
        ðŸ“ Distance: {distance} {distance_unit}
        ðŸ›£ï¸ Route: {route}
      selector:
        text:
          multiline: true

    light_traffic_title:
      name: Light Traffic Message Title
      description: Title for light traffic notification
      default: "âœ… Light Traffic"
      selector:
        text:

    light_traffic_message:
      name: Light Traffic Message
      description: Message body for light traffic (use {travel_time}, {distance}, {distance_unit}, {route})
      default: |
        Light traffic - clear roads!

        â±ï¸ Travel time: {travel_time} minutes
        ðŸ“ Distance: {distance} {distance_unit}
        ðŸ›£ï¸ Route: {route}
      selector:
        text:
          multiline: true

    failsafe_title:
      name: Failsafe Message Title
      description: Title for sensor unavailable notification
      default: "âš ï¸ Waze Sensor Problem"
      selector:
        text:

    failsafe_message:
      name: Failsafe Message
      description: Message body for sensor unavailable (use {failsafe_threshold}, {failsafe_duration}, {google_maps_link})
      default: |
        Waze sensor is not reachable after {failsafe_threshold} failed attempts ({failsafe_duration} minutes)!

        Please check traffic manually:

        ðŸ—ºï¸ Google Maps:
        {google_maps_link}
      selector:
        text:
          multiline: true

    use_waze_locations:
      name: Use Waze Sensor Origin/Destination
      description: If enabled, origin and destination will be taken from Waze sensor attributes. If disabled or unavailable, uses manual locations below.
      default: true
      selector:
        boolean:

    origin:
      name: Origin Location (Manual)
      description: Starting location (address or coordinates) - only used if "Use Waze Sensor" is disabled or Waze attributes unavailable
      default: ""
      selector:
        text:

    destination:
      name: Destination Location (Manual)
      description: Destination location (address or coordinates) - only used if "Use Waze Sensor" is disabled or Waze attributes unavailable
      default: ""
      selector:
        text:

    map_url_template:
      name: Map URL Template
      description: |
        Map service URL template for directions. Use {origin} and {destination} placeholders.
        Examples:
        - Google Maps: https://www.google.com/maps/dir/?api=1&origin={origin}&destination={destination}
        - OpenStreetMap: https://www.openstreetmap.org/directions?from={origin}&to={destination}
        - Apple Maps: https://maps.apple.com/?saddr={origin}&daddr={destination}
      default: "https://www.google.com/maps/dir/?api=1&origin={origin}&destination={destination}"
      selector:
        text:

variables:
  waze_sensor: !input waze_sensor
  traffic_state_helper: !input traffic_state_helper
  failed_attempts_counter: !input failed_attempts_counter
  telegram_target: !input telegram_target
  heavy_threshold: !input heavy_traffic_threshold
  light_threshold: !input light_traffic_threshold
  polling_interval: !input polling_interval
  failsafe_threshold: !input failsafe_threshold
  distance_unit: !input distance_unit
  active_days: !input active_days
  use_waze_locations: !input use_waze_locations
  manual_origin: !input origin
  manual_destination: !input destination
  map_url_template: !input map_url_template
  monitoring_start: !input monitoring_start
  monitoring_end: !input monitoring_end
  failsafe_duration: "{{ (polling_interval | int) * (failsafe_threshold | int) }}"
  origin: >
    {% if use_waze_locations %}
      {{ state_attr(waze_sensor, 'origin') | default(manual_origin, true) }}
    {% else %}
      {{ manual_origin }}
    {% endif %}
  destination: >
    {% if use_waze_locations %}
      {{ state_attr(waze_sensor, 'destination') | default(manual_destination, true) }}
    {% else %}
      {{ manual_destination }}
    {% endif %}
  google_maps_link: >
    {% if origin != '' and destination != '' %}
      {{ map_url_template.replace('{origin}', origin | urlencode).replace('{destination}', destination | urlencode) }}
    {% else %}
      https://www.google.com/maps
    {% endif %}
  day_map:
    mon: 0
    tue: 1
    wed: 2
    thu: 3
    fri: 4
    sat: 5
    sun: 6

trigger:
  - platform: time_pattern
    minutes: "/{{ polling_interval }}"

condition:
  - condition: time
    after: !input monitoring_start
    before: !input monitoring_end
  - condition: template
    value_template: "{{ now().weekday() in active_days | map('extract', day_map) | list }}"
    alias: "Active day check"

action:
  # Validate entity configurations
  - condition: template
    value_template: "{{ states(waze_sensor) not in ['unknown', 'unavailable', 'none'] or states(waze_sensor) | float(0) >= 0 }}"
    alias: "Validate Waze sensor exists and has a valid state"

  - condition: template
    value_template: >
      {% set options = state_attr(traffic_state_helper, 'options') %}
      {{ options is not none and 'none' in options and 'heavy' in options and 'normal' in options and 'light' in options }}
    alias: "Validate Traffic State Helper has required options (none, heavy, normal, light)"

  - condition: template
    value_template: "{{ state_attr(failed_attempts_counter, 'min') is not none and state_attr(failed_attempts_counter, 'max') is not none }}"
    alias: "Validate Failed Attempts Counter is an input_number"

  # Validate thresholds
  - condition: template
    value_template: "{{ heavy_threshold > light_threshold }}"
    alias: "Ensure heavy threshold is greater than light threshold"

  # Validate failsafe duration vs time window
  - condition: template
    value_template: >
      {% set start = strptime(monitoring_start, '%H:%M:%S') %}
      {% set end = strptime(monitoring_end, '%H:%M:%S') %}
      {% set window_minutes = (end.hour * 60 + end.minute) - (start.hour * 60 + start.minute) %}
      {{ failsafe_duration | int < (window_minutes * 0.5) }}
    alias: "Ensure failsafe duration is less than 50% of time window"

  # Update sensor with retry logic (3 attempts, 15s delays)
  - action: homeassistant.update_entity
    target:
      entity_id: "{{ waze_sensor }}"
  - delay:
      seconds: 15

  # Retry attempt 1
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(waze_sensor) in ['unknown', 'unavailable'] }}"
        sequence:
          - action: homeassistant.update_entity
            target:
              entity_id: "{{ waze_sensor }}"
          - delay:
              seconds: 15

  # Retry attempt 2
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states(waze_sensor) in ['unknown', 'unavailable'] }}"
        sequence:
          - action: homeassistant.update_entity
            target:
              entity_id: "{{ waze_sensor }}"
          - delay:
              seconds: 15

  # Branch based on sensor availability
  - choose:
      # SENSOR STILL UNAVAILABLE - Handle failsafe logic
      - conditions:
          - condition: template
            value_template: "{{ states(waze_sensor) in ['unknown', 'unavailable'] }}"
        sequence:
          # Increment failed attempts counter
          - action: input_number.increment
            target:
              entity_id: "{{ failed_attempts_counter }}"

          # Check if failsafe should trigger (3 failures AND no message sent)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ states(failed_attempts_counter) | int >= failsafe_threshold | int }}"
                  - condition: template
                    value_template: "{{ states(traffic_state_helper) == 'none' }}"
                sequence:
                  # Send failsafe message
                  - action: telegram_bot.send_message
                    data:
                      title: "{{ failsafe_title }} - {{ now().strftime('%H:%M') }}"
                      message: "{{ failsafe_message.replace('{failsafe_threshold}', failsafe_threshold | string).replace('{failsafe_duration}', failsafe_duration | string).replace('{google_maps_link}', google_maps_link) }}"
                      target: "{{ telegram_target }}"

                  # Mark state to prevent duplicate failsafe messages
                  - action: input_select.select_option
                    target:
                      entity_id: "{{ traffic_state_helper }}"
                    data:
                      option: "heavy"

          # Stop - sensor unavailable
          - stop: "Sensor unavailable after 3 attempts"

    # SENSOR IS AVAILABLE - Send traffic notifications
    default:
      # Reset failed attempts counter (sensor is working)
      - action: input_number.set_value
        target:
          entity_id: "{{ failed_attempts_counter }}"
        data:
          value: 0

      # Store travel time and current state
      - variables:
          travel_time: "{{ states(waze_sensor) | float(0) }}"
          current_state: "{{ states(traffic_state_helper) }}"
          distance: "{{ state_attr(waze_sensor, 'distance') | default('N/A', true) }}"
          route: "{{ state_attr(waze_sensor, 'route') | default('N/A', true) }}"

      # Send notifications based on traffic
      - choose:
          # Heavy traffic (> threshold)
          - conditions:
              - condition: template
                value_template: "{{ travel_time > heavy_threshold }}"
              - condition: template
                value_template: "{{ current_state != 'heavy' }}"
            sequence:
              - action: telegram_bot.send_message
                data:
                  title: "{{ heavy_traffic_title }} - {{ now().strftime('%H:%M') }}"
                  message: "{{ heavy_traffic_message.replace('{travel_time}', travel_time | round(0) | string).replace('{distance}', distance | string).replace('{distance_unit}', distance_unit).replace('{route}', route | string) }}"
                  target: "{{ telegram_target }}"
              - action: input_select.select_option
                target:
                  entity_id: "{{ traffic_state_helper }}"
                data:
                  option: "heavy"

          # Light traffic (< threshold)
          - conditions:
              - condition: template
                value_template: "{{ travel_time < light_threshold }}"
              - condition: template
                value_template: "{{ current_state != 'light' }}"
            sequence:
              - action: telegram_bot.send_message
                data:
                  title: "{{ light_traffic_title }} - {{ now().strftime('%H:%M') }}"
                  message: "{{ light_traffic_message.replace('{travel_time}', travel_time | round(0) | string).replace('{distance}', distance | string).replace('{distance_unit}', distance_unit).replace('{route}', route | string) }}"
                  target: "{{ telegram_target }}"
              - action: input_select.select_option
                target:
                  entity_id: "{{ traffic_state_helper }}"
                data:
                  option: "light"

          # Normal traffic (between thresholds)
          - conditions:
              - condition: template
                value_template: "{{ travel_time >= light_threshold and travel_time <= heavy_threshold }}"
              - condition: template
                value_template: "{{ current_state != 'normal' }}"
            sequence:
              - action: telegram_bot.send_message
                data:
                  title: "{{ normal_traffic_title }} - {{ now().strftime('%H:%M') }}"
                  message: "{{ normal_traffic_message.replace('{travel_time}', travel_time | round(0) | string).replace('{distance}', distance | string).replace('{distance_unit}', distance_unit).replace('{route}', route | string) }}"
                  target: "{{ telegram_target }}"
              - action: input_select.select_option
                target:
                  entity_id: "{{ traffic_state_helper }}"
                data:
                  option: "normal"

mode: single
